///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class R {
  R._();

  static const String hudError = 'assets/image/hud_error.png';
  static const String hudInfo = 'assets/image/hud_info.png';
  static const String hudSuccess = 'assets/image/hud_success.png';
  static const String img1 = 'assets/image/img1.png';
  static const String img2 = 'assets/image/img2.png';
  static const String img3 = 'assets/image/img3.png';
  static const String navBack = 'assets/icon/nav_back.png';
  static const String navClose = 'assets/icon/nav_close.png';
}
